<a href="https://colab.research.google.com/github/iamBHK/DiabetesPrediction/blob/main/Glucose_Level_Calculator_using_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
file = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQRp2K84U9vl_vDKZMWfrh8Sx7R628KOJvTKiOMyaS3BP60rrr0XtnxyvWkm7QsNg/pub?output=csv')

In [5]:
file.head()

Dataset for People for their Blood Glucose Level with their Superficial Body Feature readings. Age  \
0                                                  9                                                    
1                                                  9                                                    
2                                                  9                                                    
3                                                  9                                                    
4                                                 66                                                    

   Blood Glucose Level(BGL)  Diastolic Blood Pressure  \
0                        79                        73   
1                        80                        73   
2                        70                        76   
3                        70                        78   
4                       100                        96   

   Systolic Blood Pressure  Heart Rate  Body Temperature  SPO2  \
0                      118          98         98.300707    99   
1                      119         102         98.300707    94   
2                      110          81         98.300707    98   
3                      115          96         98.300707    96   
4                      144          92         97.807052    98   

   Sweating  (Y/N)  Shivering (Y/N) Diabetic/NonDiabetic (D/N)  
0                0                0                          N  
1                1                0                          N  
2                1                0                          N  
3                1                0                          N  
4                0                0                          N

In [6]:
file.describe()

Dataset for People for their Blood Glucose Level with their Superficial Body Feature readings. Age  \
count                                       16969.000000                                                    
mean                                           30.988862                                                    
std                                            25.585606                                                    
min                                             9.000000                                                    
25%                                             9.000000                                                    
50%                                            14.000000                                                    
75%                                            55.000000                                                    
max                                            77.000000                                                    

       Blood Glucose Level(BGL)  Diastolic Blood Pressure  \
count              16969.000000              16969.000000   
mean                  95.727975                 77.173493   
std                   42.992385                  7.241511   
min                   50.000000                 60.000000   
25%                   68.000000                 71.000000   
50%                   83.000000                 76.000000   
75%                  108.000000                 83.000000   
max                  250.000000                 98.000000   

       Systolic Blood Pressure    Heart Rate  Body Temperature          SPO2  \
count             16969.000000  16969.000000      16969.000000  16969.000000   
mean                118.187165     91.524191         97.356146     97.382403   
std                   7.700363     10.409780          0.813555      0.848689   
min                  95.000000     78.000000         96.000132     93.000000   
25%                 113.000000     84.000000         96.674465     97.000000   
50%                 119.000000     89.000000         97.326523     98.000000   
75%                 124.000000     95.000000         97.949904     98.000000   
max                 145.000000    130.000000         98.999792     99.000000   

       Sweating  (Y/N)  Shivering (Y/N)  
count     16969.000000     16969.000000  
mean          0.121692         0.145560  
std           0.326940         0.352674  
min           0.000000         0.000000  
25%           0.000000         0.000000  
50%           0.000000         0.000000  
75%           0.000000         0.000000  
max           1.000000         1.000000

In [7]:
file.isna().sum()

Dataset for People for their Blood Glucose Level with their Superficial Body Feature readings. Age    0
Blood Glucose Level(BGL)                                                                              0
Diastolic Blood Pressure                                                                              0
Systolic Blood Pressure                                                                               0
Heart Rate                                                                                            0
Body Temperature                                                                                      0
SPO2                                                                                                  0
Sweating  (Y/N)                                                                                       0
Shivering (Y/N)                                                                                       0
Diabetic/NonDiabetic (D/N)                                      

In [8]:
file.isnull().sum()

Dataset for People for their Blood Glucose Level with their Superficial Body Feature readings. Age    0
Blood Glucose Level(BGL)                                                                              0
Diastolic Blood Pressure                                                                              0
Systolic Blood Pressure                                                                               0
Heart Rate                                                                                            0
Body Temperature                                                                                      0
SPO2                                                                                                  0
Sweating  (Y/N)                                                                                       0
Shivering (Y/N)                                                                                       0
Diabetic/NonDiabetic (D/N)                                      

In [10]:
features = file.rename(
    columns = {
        "Dataset for People for their Blood Glucose Level with their Superficial Body Feature readings. Age" : "Age",
        "Blood Glucose Level(BGL)" : "Glucose",
        "Diastolic Blood Pressure" : "Diastolic_BP",
        "Systolic Blood Pressure" : "Systolic_BP",
        "Sweating  (Y/N)" : "Sweating",
        "Shivering (Y/N)" : "Shivering",
        "Diabetic/NonDiabetic (D/N)" : "DiaOrNot"
    }
)

In [11]:
features.head()

Age  Glucose  Diastolic_BP  Systolic_BP  Heart Rate  Body Temperature  \
0    9       79            73          118          98         98.300707   
1    9       80            73          119         102         98.300707   
2    9       70            76          110          81         98.300707   
3    9       70            78          115          96         98.300707   
4   66      100            96          144          92         97.807052   

   SPO2  Sweating  Shivering DiaOrNot  
0    99         0          0        N  
1    94         1          0        N  
2    98         1          0        N  
3    96         1          0        N  
4    98         0          0        N

In [12]:
features.Glucose

0         79
1         80
2         70
3         70
4        100
        ... 
16964     84
16965     70
16966     77
16967     86
16968     84
Name: Glucose, Length: 16969, dtype: int64

In [13]:
features.Glucose.max()

250

In [14]:
features.Glucose.min()

50

In [15]:
features.DiaOrNot.value_counts()

D    16641
N      328
Name: DiaOrNot, dtype: int64

In [18]:
D=0
N=0

for i in range(len(features.DiaOrNot)):
  if (features.DiaOrNot[i]) == "D":
    D+=1
  else:
    N+=1

print(D)
print(N)

16641
328


In [19]:
# D=0
# N=0

# while i in range(len(features.DiaOrNot)):
#   if (features.DiaOrNot[i]) == "D":
#     D+=1
#   else:
#     N+=1

# print(D)
# print(N)

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
X = features.drop(columns = {'Glucose','DiaOrNot'})

In [22]:
X

Age  Diastolic_BP  Systolic_BP  Heart Rate  Body Temperature  SPO2  \
0        9            73          118          98         98.300707    99   
1        9            73          119         102         98.300707    94   
2        9            76          110          81         98.300707    98   
3        9            78          115          96         98.300707    96   
4       66            96          144          92         97.807052    98   
...    ...           ...          ...         ...               ...   ...   
16964    9            87          127          90         96.842657    97   
16965    9            79          117          80         97.869454    98   
16966    9            82          116          93         96.766282    98   
16967    9            86          128          91         98.941036    98   
16968    9            85          117          79         97.570685    97   

       Sweating  Shivering  
0             0          0  
1             1          0  
2             1          0  
3             1          0  
4             0          0  
...         ...        ...  
16964         0          0  
16965         0          0  
16966         0          0  
16967         0          0  
16968         0          0  

[16969 rows x 8 columns]

In [23]:
Y = features.Glucose

In [24]:
Y

0         79
1         80
2         70
3         70
4        100
        ... 
16964     84
16965     70
16966     77
16967     86
16968     84
Name: Glucose, Length: 16969, dtype: int64

In [25]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()

In [26]:
scalar.fit(X)

StandardScaler()

In [27]:
standarized_data = scalar.transform(X)

In [28]:
X = standarized_data

In [29]:
X

array([[-0.85944848, -0.57634595, -0.02430669, ...,  1.90605148,
        -0.37222763, -0.41274275],
       [-0.85944848, -0.57634595,  0.10556114, ..., -3.98556343,
         2.68652813, -0.41274275],
       [-0.85944848, -0.16205559, -1.06324937, ...,  0.7277285 ,
         2.68652813, -0.41274275],
       ...,
       [-0.85944848,  0.66652513, -0.28404236, ...,  0.7277285 ,
        -0.37222763, -0.41274275],
       [-0.85944848,  1.21891228,  1.27437166, ...,  0.7277285 ,
        -0.37222763, -0.41274275],
       [-0.85944848,  1.08081549, -0.15417453, ..., -0.45059449,
        -0.37222763, -0.41274275]])

In [30]:
Y

0         79
1         80
2         70
3         70
4        100
        ... 
16964     84
16965     70
16966     77
16967     86
16968     84
Name: Glucose, Length: 16969, dtype: int64

In [31]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size=0.25, stratify=Y)

In [32]:
X_train

array([[ 0.58671975,  0.52842834,  0.49516465, ...,  0.7277285 ,
        -0.37222763, -0.41274275],
       [ 1.75928859, -1.54302346, -0.8035137 , ...,  0.7277285 ,
        -0.37222763,  2.42281664],
       [ 1.75928859,  1.77129943,  0.75490032, ...,  0.7277285 ,
        -0.37222763, -0.41274275],
       ...,
       [-0.85944848, -1.54302346, -2.36192772, ..., -0.45059449,
        -0.37222763, -0.41274275],
       [ 1.75928859, -0.85253953, -0.15417453, ...,  0.7277285 ,
        -0.37222763, -0.41274275],
       [ 0.9384904 , -0.16205559,  0.75490032, ..., -0.45059449,
        -0.37222763, -0.41274275]])

In [33]:
X_test

array([[ 1.75928859,  1.08081549,  1.53410733, ...,  0.7277285 ,
        -0.37222763, -0.41274275],
       [ 1.75928859,  0.66652513,  0.49516465, ...,  0.7277285 ,
        -0.37222763, -0.41274275],
       [-0.85944848,  0.11413798,  0.75490032, ...,  0.7277285 ,
        -0.37222763, -0.41274275],
       ...,
       [ 0.58671975, -0.16205559,  0.62503248, ...,  0.7277285 ,
        -0.37222763, -0.41274275],
       [-0.85944848, -0.43824917,  1.14450383, ..., -0.45059449,
         2.68652813,  2.42281664],
       [-0.4685922 ,  1.08081549, -0.4139102 , ..., -0.45059449,
        -0.37222763, -0.41274275]])

In [34]:
Y_train

8002      91
381       50
8842      96
12029    118
12437    121
        ... 
15795     81
9607     102
1694      63
746       60
11514    114
Name: Glucose, Length: 12726, dtype: int64

In [35]:
Y_test

9863     103
13444    127
14062    245
4911      68
12101    118
        ... 
8927      97
9523     101
6463      81
4276      68
13547    128
Name: Glucose, Length: 4243, dtype: int64

In [36]:
from sklearn import svm

In [37]:
svm = svm.SVC(kernel = 'linear')

Work with training data

In [38]:
svm.fit(X_train,Y_train)

SVC(kernel='linear')

In [39]:
Train_Predict = svm.predict(X_train)

In [40]:
from sklearn.metrics import accuracy_score

In [44]:
Train_Acc = accuracy_score(Train_Predict, Y_train)

In [45]:
Train_Acc = "{:.4f}".format(Train_Acc*100)
print(Train_Acc)

18.6076


Work with Test Data

In [46]:
svm = svm.fit(X_test, Y_test)

In [47]:
Test_Predict = svm.predict(X_test)

In [48]:
Test_Acc = accuracy_score(Test_Predict,Y_test)

In [49]:
Test_Acc = "{:.4f}".format(Test_Acc*100)
print(Test_Acc)

19.7502


In [50]:
print("Testing Accuracy is {a}% & Trainig Accuracy is {b}%" .format(a= Train_Acc, b = Test_Acc))

Testing Accuracy is 18.6076% & Trainig Accuracy is 19.7502%


Now, test with data

In [51]:
# Check = (9,84,110,94,98.64998113,98,0,0)
# Check = (9, 75,125,92,98.14764129,98,0,0)
Check = (9, 75,117,82,98.31585572,98,0,0)

In [52]:
Array = np.asarray(Check)
Array

array([  9.        ,  75.        , 117.        ,  82.        ,
        98.31585572,  98.        ,   0.        ,   0.        ])

In [53]:
Reshape = Array.reshape(1,-1)

In [54]:
Reshape

array([[  9.        ,  75.        , 117.        ,  82.        ,
         98.31585572,  98.        ,   0.        ,   0.        ]])

In [55]:
Transform = scalar.transform(Reshape)
Transform

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


array([[-0.85944848, -0.30015238, -0.15417453, -0.91495416,  1.17968459,
         0.7277285 , -0.37222763, -0.41274275]])

In [56]:
Output = svm.predict(Transform)

In [57]:
print("Glucose level is", float(Output))

Glucose level is 75.0
